title = "Eldaniz Babayev"
baseURL = 'https://s4movar.github.io'
languageCode = 'en-us'
theme = "hugo-blog-awesome"

# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable  Google Analytics, simply leave the field empty or remove the next line
googleAnalytics = '' # G-MEASUREMENT_ID


# Enable emojis globally
enableEmoji = true

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]] 
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30

[params]
  sitename = "Eldaniz"
  defaultColor = "dark" # set default color mode: dark or light
  description = "Minimal Hugo blog theme with light and dark mode support"

[params.author]
  avatar = "berserk.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Eldaniz Babayev"
  name = "Eldaniz Babayev"
  description = "Engineering Management student at Politechnika Poznańska, exploring the frontiers of Virtualization, MicroVMs, Linux internals. Currently focused Stable Diffusion Algorithms with a hands-on project in Change Detection Dataset Collection using Generative AI. "

[[params.socialIcons]]
name = "github"
url = "https://github.com/s4movar"

[[params.socialIcons]]
name = "linkedin"
url = "http://www.linkedin.com/in/eldaniiz/"

[[params.socialIcons]]
name = "email"
url = "mailto:s4movar@proton.me"
